# Generated by Django 2.0.1 on 2020-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200313_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-author',), 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
