# Generated by Django 2.0.1 on 2020-03-14 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200313_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
