# Generated by Django 2.0.1 on 2020-03-14 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blog_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.ManyToManyField(related_name='is_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
