# Generated by Django 2.0.1 on 2020-03-14 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='is_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
